### ISSUE TITLE
highlight project report attachment in data release template email

### ISSUE THREAD

**Issue by tcezard** [EdinburghGenomics/EGCG-Project-Management#105]
change the first line from 
`The data for {{ num_samples }} samples from project {{ project_id }} has been released to our Aspera server at:`
to 
`The data for {{ num_samples }} samples from project {{ project_id }} has been released to our Aspera server at the link below. Please also see attached summary report for your project.`

**Comment by lukbut** [comment]
@tcezard Can you please update this issue and link in any associated PRs as appropriate?
