### ISSUE TITLE
New script that can download genome + dbsnp 

### ISSUE THREAD

**Issue by tcezard** [EdinburghGenomics/EGCG-Project-Management#17]
We need a new script that will:
 - download genome and dbsnp data in vcf
 - index with bwa
 - index with bowtie
 - create a yaml file that will contain the information about the download.

**Comment by mwhamgenomics** [comment]
Yaml file should contain:
- ftp paths
- genome version
- dbsnp version if present
- species name
- date released

We should then add the Yaml alongside wherever the genome is stored.

**Comment by mwhamgenomics** [comment]
NCBI are going to stop supporting dbSNP for non-human species (see [here](https://www.ebi.ac.uk/about/news/press-releases/eva-issues-long-term-ids-non-human-variants)), so we should use EBI data sources instead.
