### ISSUE TITLE
Scope changes for genome downloader

### ISSUE THREAD

**Issue by mwhamgenomics** [EdinburghGenomics/EGCG-Project-Management#23]
Since NCBI is handing dbSNP support over to EBI, we'll need to be able to search EBI's Rest API for data. We've also been asked to use bespoke reference data. All this calls for a bit of scope change:

- we should add a data validation feature, decoupled from downloading
- we should be more source-agnostic, i.e. able to add documentation for bespoke genomes
- rename 'dbSNP' to 'variants'
- we should tie a dbSNP release to a genome version
  - nest dbSNP inside the Yaml entry for the genome
    - document the file path for it?
  - compatibility check script for organism, chromosome names, headers, etc.
    - GATK might be able to do this
- automated genome indexing

**Comment by tcezard** [comment]
An example of such process can be found in the README of the Gallus_gallus-5.0 genome resources
