### ISSUE TITLE
Tape recall

### ISSUE THREAD

**Issue by mwhamgenomics** [EdinburghGenomics/EGCG-Project-Management#39]
We should add a command line function to:
- find all files for a given sample
- find out how much data we would be recalling
- decide whether it's safe to recall the data
- do an `hsm_restore`
- record in the Rest API that the data is now back on Lustre

**Comment by mwhamgenomics** [comment]
If we recall the data for an old sample, it will show up as archivable by any automated archiving processes we run. How can we stop it from being archived again the moment it's been recalled?

**Comment by tcezard** [comment]
Do you mean it will show up as "deletable" from lustre?
That is a good point, any data recall  will have to mark the sample as not deletable for a a period of time.
This could be by running a LIMS step or setting a date in the Reporting app.

**Comment by tcezard** [comment]
Associated with CR424
