### ISSUE TITLE
Add check and reporting capability to gel delivery

### ISSUE THREAD

**Issue by tcezard** [EdinburghGenomics/EGCG-Project-Management#43]
We can query The REST API to get the status of the samples that have been uploaded. We need to add support for the QC status (new field in the database) and the make sure we fill in md5 status when qc status is set.
We also need to be able to report which samples were successfully uploaded/md5 checked/qc checked from the database.
We also will add email notification with status report.

**Comment by mwhamgenomics** [comment]
`GelDelivery.check_md5sum` checks GeL's API for `{'state': 'md5_passed'}` in all samples in the SQLite database where `upload_state` is successful and `md5_state` is null. `md5_passed` is quickly replaced with `qc_passed` though, so we need to pick up `qc_passed` too.

Once we've used the above to sync our SQLite database to GeL's Rest API, we need to distinguish between md5s failing and other QC failing, so we need `qc_state` and `qc_confirm_date` SQLite fields.

Finally, we need to query the SQLite database for status per sample (there may be multiple delivery attempts per sample).

**Comment by tcezard** [comment]
A new requirement was just added to prevent that any sample already uploaded successfully (with not failed flag) be uploaded again unless the `--force` option is activated.

**Comment by tcezard** [comment]
A successful delivery is defined as a upload success (rsync finished without error)
Any failure on the md5 or qc check will need to use the force option. 

without force:
 - check if upload happened:
   - if successful: do nothing 
   - if not successful: restart 
- if not happen: start from scratch

with force: restart from scratch
